apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: go-user # Name of the Kubernetes resource
spec:
  replicas: 3 # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-user # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: go-user
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: go-user
          image: "{{ image_id }}"
          ports:
            - containerPort: 7777 # Should match the port number that the Go application listens on
            - containerPort: 7778 # Should match the port number that the Go application listens on
