- hosts: localhost
  task:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('template, 'svc-lb.yml') | from_yaml }}"
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition: "{{ lookup('template', 'go-deployment.yml') } from_yaml }}"
